### ISSUE TITLE
Human Rights vs. Citizen Rights

### ISSUE THREAD

**Issue by brick-mann-0** [Staphylococcus/federal-eu-constitution#7]
Currently there doesn't seem to be a distinction between human rights and citizen rights, which I think would be quite important for certain articles.

For example, the right to freedom of press should mainly be for citizens as to be able to prevent foreign actors from interferring with elections, etc. through sponsored television and new agencies as russia currently does in all of the Europe and America. The right to vote should also mainly be reserved for citizens.

Meanwhile the right to dignity, no discrimination and The Rights of Man should apply to every Human, regardless of citizenship.

This goes especially for the right not to be expelled arbitrarily, as this should be a right of all residents and not just citizens.

**Comment by Staphylococcus** [comment]
@brick-mann-0 Those are really good points, human rights must apply to everyone, regardless of their legal status and/or citizenship. Do you have specific instances which stand out as conflation of those terms as of now?

**Comment by Staphylococcus** [comment]
@Mathew-Iron for your convenience I've created https://github.com/Staphylococcus/federal-eu-constitution/tree/feature/human-citizen-rights branch to contain edits related to this issue

**Comment by brick-mann-0** [comment]
I think Article I, IV, VI, VII, VIII, XI and XIV should be modified, as currently they would only apply to citizens, but should (in my opinion) be universal to all humans.

I intentionally didn't list Article II, III, V, IX, X, XII and XIX as I think those rights should (at least on a constitutional level) be reserved for citizens to prevent the state from being unable to act against malicious foreign actors. I don't think these rights should necesarily be generally withheld from foreigners, but I don't think it should be in the constitution.

**Comment by Staphylococcus** [comment]
@brick-mann-0 I've added the following changes: https://github.com/Staphylococcus/federal-eu-constitution/pull/9/files?short_path=90d9604#diff-90d9604c8b27c37818624a4f2f7ddada55401451a6395d140277840f81bb3a82

Regarding Article I, I feel Article VI already covers fundamental rights well, do you feel different?

**Comment by Staphylococcus** [comment]
Sorry y'all, especially @Mathew-Iron. I should've marked that pull request as draft. I've reverted the merge and opened another one here: #11 Let's allow the public some time for discussion before we merge, as this seems like a good practice to me
